---
- name: Creating OCP projects
  k8s:
    state: present
    definition: "{{ lookup('template', 'project.yml') | from_yaml }}"
    api_key: "{{ ocp_token }}"
    verify_ssl: no
  with_items: "{{ projects }}"

- name: Mapping LDAP group to the OCP admin role
  vars:
    namespace: "{{ tenant_name | lower | replace('_', '-') }}-{{ item.name | lower | replace('_', '-') }}"
    group: "{{ tenant_name | lower | replace('_', '-') }}-{{ item.name | lower | replace('_', '-') }}-admins"
    role_binding_name: "admin"
  k8s:
    state: present
    definition: "{{ lookup('template', 'role_binding.yml') | from_yaml }}"
    api_key: "{{ ocp_token }}"
    verify_ssl: no
  with_items:
    - "{{ projects }}"

- name: Mapping LDAP group to the OCP view role
  vars:
    namespace: "{{ tenant_name | lower | replace('_', '-') }}-{{ item.name | lower | replace('_', '-') }}"
    group: "{{ tenant_name | lower | replace('_', '-') }}-{{ item.name | lower | replace('_', '-') }}-users"
    role_binding_name: "view"
  k8s:
    state: present
    definition: "{{ lookup('template', 'role_binding.yml') | from_yaml }}"
    api_key: "{{ ocp_token }}"
    verify_ssl: no
  with_items:
    - "{{ projects }}"

- name: Creating resource quotas
  k8s:
    state: present
    definition: "{{ lookup('template', 'quota.yml') | from_yaml }}"
    api_key: "{{ ocp_token }}"
    verify_ssl: no
  with_items: "{{ projects }}"
...