---
- name: Deleting OCP project(s)
  k8s:
    state: absent
    definition: "{{ lookup('template', 'project.yml') | from_yaml }}"
    api_key: "{{ ocp_token }}"
    verify_ssl: no
  with_items: "{{ projects }}"
...