---
- name: Log in using service account 
  command: "oc login {{ ocp_uri }} --token={{ ocp_token }}"

- name: Creating OCP Projects
  command: "oc new-project {{ tenant_name | lower | replace('_', '-') }}-{{ item.name | lower | replace('_', '-') }} --token={{ ocp_token }}"
  with_items: "{{ projects }}"

- name: Configuring Admin users
  command: "oc adm policy add-role-to-group admin {{ tenant_name | lower | replace('_', '-') }}-{{ item.name | lower | replace('_', '-') }}-admins -n {{ tenant_name | lower | replace('_', '-') }}-{{ item.name | lower | replace('_', '-') }} --token={{ ocp_token }}"
  with_items: "{{ projects }}"

- name: Configuring Standard users
  command: "oc adm policy add-role-to-group basic-user {{ tenant_name | lower | replace('_', '-') }}-{{ item.name | lower | replace('_', '-') }}-users -n {{ tenant_name | lower | replace('_', '-') }}-{{ item.name | lower | replace('_', '-') }} --token={{ ocp_token }}"
  with_items: "{{ projects }}"

- name: Logout of service account 
  command: "oc logout"