---
- name: Removing any pre-existing resource quotas
  k8s:
    state: absent
    definition: "{{ lookup('template', 'quota.yml') | from_yaml }}"
    api_key: "{{ ocp_token }}"
    verify_ssl: no
  with_items: "{{ projects }}"

- name: Re-creating resource quotas
  k8s:
    state: present
    definition: "{{ lookup('template', 'quota.yml') | from_yaml }}"
    api_key: "{{ ocp_token }}"
    verify_ssl: no
  with_items: "{{ projects }}"