apiVersion: v1
kind: ResourceQuota
metadata:
  name: "{{ namespace }}-quota"
  namespace: "{{ namespace }}"
  selfLink: "/api/v1/namespaces/{{ namespace }}/resourcequotas/{{ namespace }}-quota"
spec:
  hard:
    cpu: "{{ item.cpu | default(2) }}"
    memory: "{{ item.memory | default(1) }}G"